/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.projeto.view;

import br.inatel.projeto.model.Anime;
import br.inatel.projeto.model.Manga;
import br.inatel.projeto.model.Studio;
import br.inatel.projeto.model.Editora;
import br.inatel.projeto.dao.AnimeDAO;
import br.inatel.projeto.dao.EditoraDAO;
import br.inatel.projeto.dao.StudioDAO;
import br.inatel.projeto.dao.MangaDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Moises Delmoro
 */
public class CadastroAnime extends javax.swing.JFrame {

    /**
     * Creates new form CadastroAnime
     */
    public CadastroAnime() {
        initComponents();

        setLocationRelativeTo(null);

        threadComboBox();

        //ComboBox_Editora.addItem(e);
    }

    private Thread combo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bot_Cadastrar = new javax.swing.JButton();
        bot_Cancelar = new javax.swing.JButton();
        txt_Nome = new javax.swing.JTextField();
        txt_Protagonista = new javax.swing.JTextField();
        txt_QuantEP = new javax.swing.JTextField();
        txt_NotaAnime = new javax.swing.JTextField();
        lbl_nome = new javax.swing.JLabel();
        lbl_protagonista = new javax.swing.JLabel();
        lbl_quantEp = new javax.swing.JLabel();
        lbl_notaAnime = new javax.swing.JLabel();
        lbl_Studio = new javax.swing.JLabel();
        ComboBox_Estudio = new javax.swing.JComboBox<>();
        ComboBox_Editora = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        PainelText_Editora = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        PainelText_Studio = new javax.swing.JTextPane();
        ComboBox_Manga = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        PainelText_Manga = new javax.swing.JTextPane();
        lbl_editora = new javax.swing.JLabel();
        lbl_manga = new javax.swing.JLabel();
        lbl_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bot_Cadastrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bot_Cadastrar.setForeground(new java.awt.Color(0, 0, 0));
        bot_Cadastrar.setText("Cadastrar");
        bot_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_Cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 343, 110, 30));

        bot_Cancelar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bot_Cancelar.setForeground(new java.awt.Color(0, 0, 0));
        bot_Cancelar.setText("Cancelar");
        bot_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 343, 110, 30));

        txt_Nome.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_Nome.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txt_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 230, -1));

        txt_Protagonista.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_Protagonista.setForeground(new java.awt.Color(0, 0, 0));
        txt_Protagonista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ProtagonistaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Protagonista, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 230, -1));

        txt_QuantEP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_QuantEP.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txt_QuantEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 212, 40, 30));

        txt_NotaAnime.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_NotaAnime.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txt_NotaAnime, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 40, -1));

        lbl_nome.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_nome.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nome.setText("Nome");
        getContentPane().add(lbl_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lbl_protagonista.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_protagonista.setForeground(new java.awt.Color(255, 255, 255));
        lbl_protagonista.setText("Protagonista");
        getContentPane().add(lbl_protagonista, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lbl_quantEp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_quantEp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_quantEp.setText("Quantidade de episódios");
        getContentPane().add(lbl_quantEp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        lbl_notaAnime.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_notaAnime.setForeground(new java.awt.Color(255, 255, 255));
        lbl_notaAnime.setText("Nota do Anime");
        getContentPane().add(lbl_notaAnime, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        lbl_Studio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_Studio.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Studio.setText("Studio");
        getContentPane().add(lbl_Studio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        ComboBox_Estudio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ComboBox_Estudio.setForeground(new java.awt.Color(0, 0, 0));
        ComboBox_Estudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_EstudioActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBox_Estudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 90, 30));

        ComboBox_Editora.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ComboBox_Editora.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(ComboBox_Editora, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 90, 30));

        PainelText_Editora.setEditable(false);
        PainelText_Editora.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        PainelText_Editora.setForeground(new java.awt.Color(0, 0, 0));
        PainelText_Editora.setOpaque(false);
        jScrollPane3.setViewportView(PainelText_Editora);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 280, 90));

        PainelText_Studio.setEditable(false);
        PainelText_Studio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        PainelText_Studio.setForeground(new java.awt.Color(0, 0, 0));
        PainelText_Studio.setOpaque(false);
        jScrollPane4.setViewportView(PainelText_Studio);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 280, 100));

        ComboBox_Manga.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ComboBox_Manga.setForeground(new java.awt.Color(0, 0, 0));
        ComboBox_Manga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_MangaActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBox_Manga, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 90, 30));

        PainelText_Manga.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        PainelText_Manga.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane5.setViewportView(PainelText_Manga);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 280, 120));

        lbl_editora.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_editora.setForeground(new java.awt.Color(255, 255, 255));
        lbl_editora.setText("Editora");
        getContentPane().add(lbl_editora, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        lbl_manga.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_manga.setForeground(new java.awt.Color(255, 255, 255));
        lbl_manga.setText("Mangá");
        getContentPane().add(lbl_manga, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        lbl_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/inatel/projeto/img/05.jpg"))); // NOI18N
        getContentPane().add(lbl_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_CadastrarActionPerformed
        // TODO add your handling code here:

        br.inatel.projeto.dao.AnimeDAO AnimeDAO = new AnimeDAO();
        Anime animeAux = new Anime();

        animeAux.setNome(txt_Nome.getText());
        animeAux.setProtagonista(txt_Protagonista.getText());
        try{
        animeAux.setQuantidadeEP(Integer.parseInt(txt_QuantEP.getText()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Dados ínvalidos!!!");
        }
        animeAux.setNotaAnime(txt_NotaAnime.getText());
        animeAux.setEditoraidEditora(ComboBox_Editora.getSelectedIndex());
        animeAux.setStudioidStudio(ComboBox_Estudio.getSelectedIndex());
        animeAux.setMangaidManga(ComboBox_Manga.getSelectedIndex()+1);

        AnimeDAO.inserirAnime(animeAux);

        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_bot_CadastrarActionPerformed

    private void bot_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_CancelarActionPerformed
        // TODO add your handling code here:
        
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_bot_CancelarActionPerformed

    private void txt_ProtagonistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ProtagonistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ProtagonistaActionPerformed

    private void ComboBox_EstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_EstudioActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ComboBox_EstudioActionPerformed

    private void ComboBox_MangaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_MangaActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_ComboBox_MangaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadastroAnime().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_Editora;
    private javax.swing.JComboBox<String> ComboBox_Estudio;
    private javax.swing.JComboBox<String> ComboBox_Manga;
    private javax.swing.JTextPane PainelText_Editora;
    private javax.swing.JTextPane PainelText_Manga;
    private javax.swing.JTextPane PainelText_Studio;
    private javax.swing.JButton bot_Cadastrar;
    private javax.swing.JButton bot_Cancelar;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbl_Studio;
    private javax.swing.JLabel lbl_editora;
    private javax.swing.JLabel lbl_fundo;
    private javax.swing.JLabel lbl_manga;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_notaAnime;
    private javax.swing.JLabel lbl_protagonista;
    private javax.swing.JLabel lbl_quantEp;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_NotaAnime;
    private javax.swing.JTextField txt_Protagonista;
    private javax.swing.JTextField txt_QuantEP;
    // End of variables declaration//GEN-END:variables

    public void threadComboBox() {

        ArrayList<Studio> ArrayStudio;
        StudioDAO st = new StudioDAO();
        ArrayStudio = st.buscarIdStudio();
        for (Studio studio : ArrayStudio) {
            ComboBox_Estudio.addItem("Id = " + studio.getIdStudio());
        }

        ArrayList<Editora> ArrayEditora;
        EditoraDAO ed = new EditoraDAO();
        ArrayEditora = ed.buscarIdEditora();
        for (Editora editora : ArrayEditora) {
            ComboBox_Editora.addItem("Id = " + editora.getIdEditora());
        }

        ArrayList<Manga> ArrayManga;
        MangaDAO ma = new MangaDAO();
        ArrayManga = ma.buscarIdManga();
        for (Manga manga : ArrayManga) {
            ComboBox_Manga.addItem("Id = " + manga.getIdManga());
        }

        combo = new Thread() {

            @Override
            public void run() {
                while (true) {
                    Studio std = new Studio();
                    std = (Studio) st.buscarStudio(ComboBox_Estudio.getSelectedIndex());
                    PainelText_Studio.setText(std.toStringLabel()+"");

                    Editora edi = new Editora();
                    edi = (Editora) ed.buscarEditora(ComboBox_Editora.getSelectedIndex());
                    PainelText_Editora.setText(edi.toStringLabel()+"");

                    Manga mg = new Manga();
                    mg = (Manga) ma.buscarManga(ComboBox_Manga.getSelectedIndex() + 1);
                    PainelText_Manga.setText(mg.toStringLabel()+"");

                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        //Logger.getLogger(CadastroAnime.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }

            }

        };

        combo.start();
    }

}
