/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.projeto.view;

import br.inatel.projeto.dao.MangaDAO;
import br.inatel.projeto.model.Manga;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Moises Delmoro
 */
public class CadastroManga extends javax.swing.JFrame {

    /**
     * Creates new form CadastroManga
     */
    public CadastroManga() {
        initComponents();

        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nome = new javax.swing.JLabel();
        lbl_autor = new javax.swing.JLabel();
        lbl_QuantCap = new javax.swing.JLabel();
        lbl_edicao = new javax.swing.JLabel();
        lbl_DataLancamento = new javax.swing.JLabel();
        bot_Cadastrar = new javax.swing.JButton();
        bot_Cancelar = new javax.swing.JButton();
        txt_nome = new javax.swing.JTextField();
        txt_autor = new javax.swing.JTextField();
        txt_QuantidadeCap = new javax.swing.JTextField();
        txt_edicao = new javax.swing.JTextField();
        txt_DataLancamento = new javax.swing.JFormattedTextField();
        lbl_Nomes = new javax.swing.JLabel();
        lbl_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nome.setBackground(new java.awt.Color(255, 255, 255));
        lbl_nome.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_nome.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nome.setLabelFor(txt_nome);
        lbl_nome.setText("Nome");
        getContentPane().add(lbl_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        lbl_autor.setBackground(new java.awt.Color(255, 255, 255));
        lbl_autor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_autor.setForeground(new java.awt.Color(255, 255, 255));
        lbl_autor.setText("Autor");
        getContentPane().add(lbl_autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));

        lbl_QuantCap.setBackground(new java.awt.Color(255, 255, 255));
        lbl_QuantCap.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_QuantCap.setForeground(new java.awt.Color(255, 255, 255));
        lbl_QuantCap.setText("Quantidade de capítulos");
        getContentPane().add(lbl_QuantCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        lbl_edicao.setBackground(new java.awt.Color(255, 255, 255));
        lbl_edicao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_edicao.setForeground(new java.awt.Color(255, 255, 255));
        lbl_edicao.setText("Edição");
        getContentPane().add(lbl_edicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        lbl_DataLancamento.setBackground(new java.awt.Color(255, 255, 255));
        lbl_DataLancamento.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_DataLancamento.setForeground(new java.awt.Color(255, 255, 255));
        lbl_DataLancamento.setText("Data de lançamento");
        getContentPane().add(lbl_DataLancamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        bot_Cadastrar.setBackground(new java.awt.Color(255, 255, 255));
        bot_Cadastrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bot_Cadastrar.setForeground(new java.awt.Color(0, 0, 0));
        bot_Cadastrar.setText("Cadastrar");
        bot_Cadastrar.setBorderPainted(false);
        bot_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_Cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 110, 30));

        bot_Cancelar.setBackground(new java.awt.Color(255, 255, 255));
        bot_Cancelar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bot_Cancelar.setForeground(new java.awt.Color(0, 0, 0));
        bot_Cancelar.setText("Cancelar");
        bot_Cancelar.setBorderPainted(false);
        bot_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 110, 30));

        txt_nome.setBackground(new java.awt.Color(255, 255, 255));
        txt_nome.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_nome.setForeground(new java.awt.Color(0, 0, 0));
        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 170, 30));

        txt_autor.setBackground(new java.awt.Color(255, 255, 255));
        txt_autor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_autor.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txt_autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 170, 30));

        txt_QuantidadeCap.setBackground(new java.awt.Color(255, 255, 255));
        txt_QuantidadeCap.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_QuantidadeCap.setForeground(new java.awt.Color(0, 0, 0));
        txt_QuantidadeCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_QuantidadeCapActionPerformed(evt);
            }
        });
        getContentPane().add(txt_QuantidadeCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 40, 30));

        txt_edicao.setBackground(new java.awt.Color(255, 255, 255));
        txt_edicao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_edicao.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txt_edicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 40, 30));

        txt_DataLancamento.setBackground(new java.awt.Color(255, 255, 255));
        txt_DataLancamento.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txt_DataLancamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_DataLancamento.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_DataLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DataLancamentoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_DataLancamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 80, -1));

        lbl_Nomes.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_Nomes.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nomes.setText("Cadastrado de Mangás");
        getContentPane().add(lbl_Nomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbl_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/inatel/projeto/img/04.jpg"))); // NOI18N
        lbl_fundo.setText("jLabel1");
        getContentPane().add(lbl_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeActionPerformed

    private void txt_QuantidadeCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_QuantidadeCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_QuantidadeCapActionPerformed

    private void bot_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_CancelarActionPerformed
        // TODO add your handling code here:

        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_bot_CancelarActionPerformed

    private void bot_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_CadastrarActionPerformed
        // TODO add your handling code here:

        br.inatel.projeto.dao.MangaDAO mangaDAO = new MangaDAO();

        Manga mangaAux = new Manga();
        try {
            // mangaAux.setIdManga(Integer.parseInt(txt_idManga.getText()));
            mangaAux.setNome(txt_nome.getText());
            mangaAux.setAutor(txt_autor.getText());
            try {
                mangaAux.setQuantCap(Integer.parseInt(txt_QuantidadeCap.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Dados ínvalidos!!!");
                
            }
            mangaAux.setEdicao(txt_edicao.getText());

            String x = txt_DataLancamento.getText();
            try {
                DateTimeFormatter f = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                LocalDate data = LocalDate.parse(x, f);

                String aux1 = data.toString();

                mangaAux.setDataLancamento(aux1);
                //JOptionPane.showMessageDialog(null, aux1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Ínvalida!!!");
                
            }

            mangaDAO.inserirManga(mangaAux);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro, entrada inválida!!!");
            
        }
        JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!!!");
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_bot_CadastrarActionPerformed

    private void txt_DataLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DataLancamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DataLancamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroManga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroManga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroManga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroManga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroManga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_Cadastrar;
    private javax.swing.JButton bot_Cancelar;
    private javax.swing.JLabel lbl_DataLancamento;
    private javax.swing.JLabel lbl_Nomes;
    private javax.swing.JLabel lbl_QuantCap;
    private javax.swing.JLabel lbl_autor;
    private javax.swing.JLabel lbl_edicao;
    private javax.swing.JLabel lbl_fundo;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JFormattedTextField txt_DataLancamento;
    private javax.swing.JTextField txt_QuantidadeCap;
    private javax.swing.JTextField txt_autor;
    private javax.swing.JTextField txt_edicao;
    private javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables
}
