/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.projeto.view;

import br.inatel.projeto.dao.AnimeDAO;
import br.inatel.projeto.model.Anime;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Moises Delmoro
 */
public class ListarAnime extends javax.swing.JFrame {

    /**
     * Creates new form ListarAnime
     */
    public ListarAnime() {

        initComponents();
        setLocationRelativeTo(null);

        threadComboBox();
    }

    private Thread combo;
    int cont=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Studio = new javax.swing.JLabel();
        ComboBox_Estudio = new javax.swing.JComboBox<>();
        lbl_editora = new javax.swing.JLabel();
        ComboBox_Manga = new javax.swing.JComboBox<>();
        ComboBox_Editora = new javax.swing.JComboBox<>();
        lbl_manga = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        txt_Nome = new javax.swing.JTextField();
        lbl_protagonista = new javax.swing.JLabel();
        txt_Protagonista = new javax.swing.JTextField();
        lbl_quantEp = new javax.swing.JLabel();
        txt_QuantEP = new javax.swing.JTextField();
        lbl_notaAnime = new javax.swing.JLabel();
        txt_NotaAnime = new javax.swing.JTextField();
        lbl_Nomes = new javax.swing.JLabel();
        ComboBox_Animes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        PainelText_Animes = new javax.swing.JTextPane();
        btn_Voltar1 = new javax.swing.JButton();
        Bot_Editar = new javax.swing.JButton();
        Bot_Excluir = new javax.swing.JButton();
        lbl_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Studio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_Studio.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Studio.setText("Studio");
        getContentPane().add(lbl_Studio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        ComboBox_Estudio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ComboBox_Estudio.setForeground(new java.awt.Color(0, 0, 0));
        ComboBox_Estudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_EstudioActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBox_Estudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 140, 30));

        lbl_editora.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_editora.setForeground(new java.awt.Color(255, 255, 255));
        lbl_editora.setText("Editora");
        getContentPane().add(lbl_editora, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        ComboBox_Manga.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ComboBox_Manga.setForeground(new java.awt.Color(0, 0, 0));
        ComboBox_Manga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_MangaActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBox_Manga, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 140, 30));

        ComboBox_Editora.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ComboBox_Editora.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(ComboBox_Editora, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 140, 30));

        lbl_manga.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_manga.setForeground(new java.awt.Color(255, 255, 255));
        lbl_manga.setText("Mangá");
        getContentPane().add(lbl_manga, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        lbl_nome.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_nome.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nome.setText("Nome:");
        getContentPane().add(lbl_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        txt_Nome.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_Nome.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txt_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 200, -1));

        lbl_protagonista.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_protagonista.setForeground(new java.awt.Color(255, 255, 255));
        lbl_protagonista.setText("Protagonista:");
        getContentPane().add(lbl_protagonista, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        txt_Protagonista.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_Protagonista.setForeground(new java.awt.Color(0, 0, 0));
        txt_Protagonista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ProtagonistaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Protagonista, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 140, -1));

        lbl_quantEp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_quantEp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_quantEp.setText("Quantidade de episódios:");
        getContentPane().add(lbl_quantEp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        txt_QuantEP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_QuantEP.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txt_QuantEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 40, 30));

        lbl_notaAnime.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_notaAnime.setForeground(new java.awt.Color(255, 255, 255));
        lbl_notaAnime.setText("Nota do Anime:");
        getContentPane().add(lbl_notaAnime, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        txt_NotaAnime.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_NotaAnime.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txt_NotaAnime, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 40, -1));

        lbl_Nomes.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_Nomes.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nomes.setText("Animes Cadastrados");
        getContentPane().add(lbl_Nomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(ComboBox_Animes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 190, -1));

        jScrollPane1.setViewportView(PainelText_Animes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 190, 270));

        btn_Voltar1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_Voltar1.setText("Cancelar");
        btn_Voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Voltar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Voltar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 110, 40));

        Bot_Editar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Bot_Editar.setText("Editar");
        Bot_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_EditarActionPerformed(evt);
            }
        });
        getContentPane().add(Bot_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 110, 40));

        Bot_Excluir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Bot_Excluir.setText("Excluir");
        Bot_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_ExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(Bot_Excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 110, 40));

        lbl_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/inatel/projeto/img/01.jpg"))); // NOI18N
        getContentPane().add(lbl_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Voltar1ActionPerformed
        // TODO add your handling code here:

        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_Voltar1ActionPerformed

    private void Bot_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_EditarActionPerformed
        // TODO add your handling code here:
        if (cont % 2 == 0) {

            Bot_Editar.setText("Atualizar");
            
            AnimeDAO animeDAO = new AnimeDAO();
            Anime animeAux = new Anime();
            animeAux = animeDAO.buscarAnime(ComboBox_Animes.getSelectedIndex() + 1);

            txt_Nome.setText(animeAux.getNome());
            txt_Protagonista.setText(animeAux.getProtagonista());
            txt_QuantEP.setText(animeAux.getQuantidadeEP() + "");
            txt_NotaAnime.setText(animeAux.getNotaAnime());
            ComboBox_Estudio.setSelectedIndex(animeAux.getStudioidStudio());
            ComboBox_Editora.setSelectedIndex(animeAux.getEditoraidEditora());
            ComboBox_Manga.setSelectedIndex(animeAux.getMangaidManga());

        } else {

            Anime an = new Anime();

            an.setNome(txt_Nome.getText());
            an.setProtagonista(txt_Protagonista.getText());
            an.setQuantidadeEP(Integer.parseInt(txt_QuantEP.getText()));
            an.setNotaAnime(txt_NotaAnime.getText());
            an.setStudioidStudio(ComboBox_Estudio.getSelectedIndex());
            an.setEditoraidEditora(ComboBox_Editora.getSelectedIndex());
            an.setMangaidManga(ComboBox_Manga.getSelectedIndex());
/*
            AnimeDAO anDAO = new AnimeDAO();
            anDAO.editar(ComboBox_mangas.getSelectedIndex() + 1, aEd);
/*/
            txt_Nome.setText("");
            txt_Protagonista.setText("");
            txt_QuantEP.setText("");
            txt_NotaAnime.setText("");
            Bot_Editar.setText("Editar");
            
            JOptionPane.showMessageDialog(null, "Atualizado com sucesso!!!");
        }
        cont++;
    }//GEN-LAST:event_Bot_EditarActionPerformed

    private void Bot_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_ExcluirActionPerformed
        // TODO add your handling code here:
       /* MangaDAO mangaDAO = new MangaDAO();
        Manga mangaAux = new Manga();
        mangaDAO.deletarManga(ComboBox_mangas.getSelectedIndex() + 1);
        JOptionPane.showMessageDialog(null, "Excluído com sucesso!!!");

        ComboBox_mangas.removeAllItems();

        ArrayList<Manga> ArrayManga;
        MangaDAO ma = new MangaDAO();
        ArrayManga = ma.buscarIdManga();
        for (Manga mang : ArrayManga) {
            ComboBox_mangas.addItem(mang.getNome());
        }

        txt_nome.setText("");
        txt_autor.setText("");
        txt_quantCap.setText("");
        txt_edicao.setText("");
        txt_Data.setText("");
        Bot_Editar.setText("Editar");*/
    }//GEN-LAST:event_Bot_ExcluirActionPerformed

    private void txt_ProtagonistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ProtagonistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ProtagonistaActionPerformed

    private void ComboBox_EstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_EstudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_EstudioActionPerformed

    private void ComboBox_MangaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_MangaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ComboBox_MangaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarAnime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bot_Editar;
    private javax.swing.JButton Bot_Excluir;
    private javax.swing.JComboBox<String> ComboBox_Animes;
    private javax.swing.JComboBox<String> ComboBox_Editora;
    private javax.swing.JComboBox<String> ComboBox_Estudio;
    private javax.swing.JComboBox<String> ComboBox_Manga;
    private javax.swing.JTextPane PainelText_Animes;
    private javax.swing.JButton btn_Voltar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Nomes;
    private javax.swing.JLabel lbl_Studio;
    private javax.swing.JLabel lbl_editora;
    private javax.swing.JLabel lbl_fundo;
    private javax.swing.JLabel lbl_manga;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_notaAnime;
    private javax.swing.JLabel lbl_protagonista;
    private javax.swing.JLabel lbl_quantEp;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_NotaAnime;
    private javax.swing.JTextField txt_Protagonista;
    private javax.swing.JTextField txt_QuantEP;
    // End of variables declaration//GEN-END:variables

    public void threadComboBox() {

        ArrayList<Anime> ArrayAnime;
        AnimeDAO an = new AnimeDAO();
        ArrayAnime = an.buscarIdAnime();
        for (Anime anime : ArrayAnime) {
            ComboBox_Animes.addItem(1+"");
        }

        combo = new Thread() {

            @Override
            public void run() {
                while (true) {

                    Anime ani = new Anime();
                    ani = (Anime) an.buscarAnime(ComboBox_Animes.getSelectedIndex()+1);
                    PainelText_Animes.setText(ani.toStringLabel());

                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        //Logger.getLogger(CadastroAnime.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }

            }

        };

        combo.start();
    }

}
