/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.projeto.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Moises Delmoro
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_NomeLogin = new javax.swing.JTextField();
        bot_Cancelar = new javax.swing.JButton();
        bot_Entrar = new javax.swing.JButton();
        txt_Senha = new javax.swing.JPasswordField();
        lbl_Usuario = new javax.swing.JLabel();
        lbl_Senha = new javax.swing.JLabel();
        lbl_Colinhakkkk = new javax.swing.JLabel();
        lbl_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_NomeLogin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txt_NomeLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 120, 30));

        bot_Cancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bot_Cancelar.setText("Cancelar");
        bot_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 327, 120, -1));

        bot_Entrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bot_Entrar.setText("Entrar");
        bot_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_EntrarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 130, 40));

        txt_Senha.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txt_Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 110, 30));

        lbl_Usuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Usuario.setText("Usuário");
        getContentPane().add(lbl_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        lbl_Senha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Senha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Senha.setText("Senha");
        getContentPane().add(lbl_Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        lbl_Colinhakkkk.setText("admin 123");
        getContentPane().add(lbl_Colinhakkkk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 20));

        lbl_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/inatel/projeto/img/04.jpg"))); // NOI18N
        getContentPane().add(lbl_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_EntrarActionPerformed
        // TODO add your handling code here:
        
        if (txt_NomeLogin.getText().equals("admin") && txt_Senha.getText().equals("123")) {

            new Menu().setVisible(true);
            dispose();
            
        } else {
            JOptionPane.showMessageDialog(null, "Logín Ínvalido!!!");
            new Login().setVisible(true);
            dispose();
            
        }


    }//GEN-LAST:event_bot_EntrarActionPerformed

    private void bot_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_CancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bot_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_Cancelar;
    private javax.swing.JButton bot_Entrar;
    private javax.swing.JLabel lbl_Colinhakkkk;
    private javax.swing.JLabel lbl_Senha;
    private javax.swing.JLabel lbl_Usuario;
    private javax.swing.JLabel lbl_fundo;
    private javax.swing.JTextField txt_NomeLogin;
    private javax.swing.JPasswordField txt_Senha;
    // End of variables declaration//GEN-END:variables
}
